### ISSUE TITLE
there maybe some bug with the new relic pd missile

### ISSUE THREAD

**Issue by magiclu** [theDragn/ApexDesignCollective#2]
![image](https://github.com/theDragn/ApexDesignCollective/assets/3338197/22603f16-7679-4f55-b2dd-d48266aa33f1)
![image](https://github.com/theDragn/ApexDesignCollective/assets/3338197/893b198e-3b07-4732-a56c-41c927787f48)

game will crash.
If i unequip it.it will be fine

**Comment by theDragn** [comment]
Yep, missed a null check. I'll fix it first thing tomorrow and have a patch out soon.
